name: Terraform Infra + Deploy Node.js App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_WORK_DIR: project-root/infra
  NODE_SRC_DIR: src
  NODE_VERSION: "20"
  AZURE_WEBAPP_NAME: nodejs-app-aishwarya-dev   # must match dev.tfvars webapp_name

jobs:

  # ---------------------------
  # 1) TERRAFORM INFRASTRUCTURE
  # ---------------------------
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform init

      - name: Terraform Apply (using dev.tfvars)
        working-directory: ${{ env.TF_WORK_DIR }}
        run: terraform apply -auto-approve -var-file=dev.tfvars


  # ---------------------------
  # 2) DEPLOY NODE.JS APP
  # ---------------------------
  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.NODE_SRC_DIR }}
        run: npm ci

      - name: Build (optional)
        working-directory: ${{ env.NODE_SRC_DIR }}
        run: npm run build --if-present

      - name: Zip Artifact
        run: |
          cd ${{ env.NODE_SRC_DIR }}
          zip -r ../app.zip . -x "node_modules/*"
          cd ..

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app.zip
